change default dtype to int
CINPLA/pyopenephys pull request #20
Opened 2021-02-09 18:36 UTC by luiztauffer

float values can be obtained with gain

2021-02-09 18:54 UTC, luiztauffer commented
@alejoe91 I changed the default dtype to int16, we can use the gain value to get traces in float (as it was before). The RecordingExtractor does that already, I'll check if that needs any update.
However, I think there's something wrong with the values in Volts obtained with int16 * 0.195 (the fixed value for gain in OpenEphys), since the numerical values are fluctuating between +/- 300

2021-02-10 08:14 UTC, alejoe91 commented
Hi Luiz,

I double checked and multiplying the ADC value by the bit_volts value returns the uV value (https://groups.google.com/g/open-ephys/c/9CKgVPoEF7M?pli=1). 

Note that +/- 300 uV is perfectlu fine if the data is raw (contains LFP). These are typical ecephys voltage ranges.

I agree we could use `int16` by default for the Continuous format

2021-02-10 08:15 UTC, alejoe91 commented on pyopenephys/core.py
> +            gain = 0.195 / 2**15
```suggestion
            gain = 0.195
```

2021-02-10 08:16 UTC, alejoe91 commented on pyopenephys/openephys_tools.py
> +def loadContinuous(filepath, dtype=np.int16):
I think it's safer to have these as strings
```suggestion
def loadContinuous(filepath, dtype='int16'):  
```

2021-02-10 12:55 UTC, alejoe91 requested changes

2021-02-10 12:55 UTC, alejoe91 commented on pyopenephys/openephys_tools.py
> +    assert dtype in (float, 'int16'), \
Can you make float also a str?

2021-02-10 12:56 UTC, luiztauffer commented on pyopenephys/openephys_tools.py
> +    assert dtype in (float, 'int16'), \
sure

2021-02-10 12:59 UTC, luiztauffer commented on pyopenephys/openephys_tools.py
> +    assert dtype in (float, 'int16'), \
done

2021-02-13 13:31 UTC, alejoe91 approved these changes

2021-02-13 13:31 UTC, merged